# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b3f1b9dce28172c4da691ea6cae102ef2ae464bba4906ac427603027838ee22109a49cd4fe2fbfa524993306920ba262231f8bfbadc4fefd7bb2a00fcf48b1d

test:
  secret_key_base: 47ea955181adc6ba89677e050236f849ffcd48ca4103377427720018236be83c1988dc0b3c0e00ae2a65f566dea2c08b79231a1c935580911ab73092f2c149f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
